$codesDir = "scripts/codes"
$meta1 = "nexus-admin|Nexus Admin Dashboard|Production admin panel with live canvas charts, searchable user table, animated counters, and dark-mode glassmorphic UI.|Dashboards|892|NexusTeam|14.2k|1 day ago"
$html1 = @"
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nexus Admin</title>
<style>
*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui,sans-serif}body{background:#0f172a;color:#e2e8f0;display:flex;min-height:100vh}.sidebar{width:220px;background:#1e293b;border-right:1px solid #334155;padding:20px}.sidebar h2{color:#3b82f6;margin-bottom:24px;font-size:1rem}.sidebar nav a{display:flex;align-items:center;gap:8px;padding:8px 12px;border-radius:8px;color:#94a3b8;text-decoration:none;font-size:.875rem;margin-bottom:4px}.sidebar nav a.active,.sidebar nav a:hover{background:#334155;color:#fff}.main{flex:1;padding:24px}.headerbar{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.headerbar h1{font-size:1.25rem}.search-bar input{background:#1e293b;border:1px solid #334155;border-radius:8px;padding:8px 14px;color:#e2e8f0;width:220px;outline:0;font-family:inherit}.search-bar input:focus{border-color:#3b82f6}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:20px}.stat-card{background:#1e293b;border:1px solid #334155;border-radius:10px;padding:16px}.stat-card .lbl{font-size:.7rem;color:#64748b;text-transform:uppercase;letter-spacing:.5px}.stat-card .val{font-size:1.5rem;font-weight:700;margin-top:4px}.stat-card .chg{font-size:.75rem;margin-top:4px}.chg.up{color:#10b981}.chg.down{color:#ef4444}.chart-box{background:#1e293b;border:1px solid #334155;border-radius:10px;padding:16px;margin-bottom:20px}.chart-box h3{color:#94a3b8;font-size:.7rem;text-transform:uppercase;margin-bottom:12px}canvas{width:100%!important;height:180px!important}.table-box{background:#1e293b;border:1px solid #334155;border-radius:10px;padding:16px}.table-box h3{color:#94a3b8;font-size:.7rem;text-transform:uppercase;margin-bottom:12px}.table-box input{background:#0f172a;border:1px solid #334155;border-radius:6px;padding:6px 10px;color:#e2e8f0;width:200px;margin-bottom:12px;outline:0;font-family:inherit}table{width:100%;border-collapse:collapse;font-size:.8rem}th,td{padding:8px 8px;text-align:left;border-bottom:1px solid #334155}th{color:#64748b;font-weight:600}td .status{padding:2px 8px;border-radius:99px;font-size:.7rem}.status.active{background:#10b98120;color:#10b981}.status.pending{background:#f59e0b20;color:#f59e0b}.status.suspended{background:#ef444420;color:#ef4444}.grid-2{display:grid;grid-template-columns:1fr 1fr;gap:16px}
</style>
</head>
<body>
<div class="sidebar"><h2>Nexus</h2><nav><a href="#" class="active">Dashboard</a><a href="#">Users</a><a href="#">Orders</a><a href="#">Settings</a><a href="#">Reports</a></nav></div>
<div class="main"><div class="headerbar"><h1>Dashboard</h1><div class="search-bar"><input id="globalSearch" placeholder="Search anything..." oninput="filterTable()"></div></div>
<div class="stats"><div class="stat-card"><div class="lbl">Revenue</div><div class="val" id="rev">$0</div><div class="chg up">+12.5%</div></div><div class="stat-card"><div class="lbl">Users</div><div class="val" id="users">0</div><div class="chg up">+8.2%</div></div><div class="stat-card"><div class="lbl">Orders</div><div class="val" id="orders">0</div><div class="chg up">+3.7%</div></div><div class="stat-card"><div class="lbl">Growth</div><div class="val" id="growth">0%</div><div class="chg up">+2.1%</div></div></div>
<div class="grid-2"><div class="chart-box"><h3>Weekly Revenue</h3><canvas id="revChart"></canvas></div><div class="chart-box"><h3>User Growth</h3><canvas id="userChart"></canvas></div></div>
<div class="table-box"><h3>Recent Users</h3><input id="userSearch" placeholder="Search users..." oninput="filterTable()"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody id="userTable"></tbody></table></div></div>
<script>
const users=[{n:"Alice Chen",e:"alice@dev.com",r:"Admin",s:"active"},{n:"Bob Smith",e:"bob@startup.io",r:"Editor",s:"active"},{n:"Carol Davis",e:"carol@corp.net",r:"Viewer",s:"pending"},{n:"Dave Wilson",e:"dave@agency.co",r:"Editor",s:"active"},{n:"Eve Johnson",e:"eve@freelance.com",r:"Viewer",s:"suspended"}];
function renderUsers(list){document.getElementById("userTable").innerHTML=list.map(u=>"<tr><td>"+u.n+"</td><td>"+u.e+"</td><td>"+u.r+'</td><td><span class="status '+u.s+'">'+u.s+"</span></td></tr>").join("")}
renderUsers(users);
window.filterTable=function(){const q=document.getElementById("userSearch").value.toLowerCase();renderUsers(users.filter(function(u){return u.n.toLowerCase().includes(q)||u.e.toLowerCase().includes(q)}))};
function drawChart(id,data,color){const c=document.getElementById(id);if(!c)return;const ctx=c.getContext("2d"),dpr=window.devicePixelRatio||1,rect=c.parentElement.getBoundingClientRect();c.width=rect.width*dpr;c.height=180*dpr;c.style.width=rect.width+"px";c.style.height="180px";ctx.scale(dpr,dpr);const w=rect.width,h=180,pt=20,pl=20,pr=10,cw=w-pl-pr,ch=h-pt*2,max=Math.max(...data),grd=ctx.createLinearGradient(0,pt,0,h-pt);grd.addColorStop(0,color+"80");grd.addColorStop(1,color+"00");ctx.beginPath();data.forEach(function(v,i){var x=pl+i/(data.length-1)*cw,y=pt+ch-v/max*ch;i===0?ctx.moveTo(x,y):ctx.lineTo(x,y)});data.forEach(function(v,i){ctx.lineTo(pl+i/(data.length-1)*cw,pt+ch)});ctx.closePath();ctx.fillStyle=grd;ctx.fill();ctx.beginPath();data.forEach(function(v,i){var x=pl+i/(data.length-1)*cw,y=pt+ch-v/max*ch;i===0?ctx.moveTo(x,y):ctx.lineTo(x,y)});ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke()}
function animateVal(el,target,dur){let s=0,st;const step=function(ts){if(!st)st=ts;const p=Math.min((ts-st)/dur,1),v=Math.floor(p*target);el.textContent=el.id==="growth"?v+"%":"$"+v;p<1&&requestAnimationFrame(step)};requestAnimationFrame(step)}
animateVal(document.getElementById("rev"),28450,1200);animateVal(document.getElementById("users"),1842,1200);animateVal(document.getElementById("orders"),563,1200);
const ge=document.getElementById("growth");let g=0;const gi=setInterval(function(){g+=.5;ge.textContent=g.toFixed(1)+"%";g>=24.8&&clearInterval(gi)},30);
drawChart("revChart",[4200,5800,4900,7200,8100,6500,9400,10200,8800,11500,9800,12800],"#3b82f6");drawChart("userChart",[320,480,560,720,890,650,980,1100,950,1240,1180,1420],"#10b981")
</script>
</body>
</html>
"@
$b64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($html1))
Set-Content -Path "$codesDir/nexus-admin.txt" -Value ($meta1 + "`n" + $b64) -NoNewline
Write-Host "nexus-admin done: $($b64.Length) chars"
